### ISSUE TITLE
doesn't work in background

### ISSUE THREAD

**Issue by farokhze** [Dev-hwang/geofence_service#5]
Hey,
I use this package to send a notification when the user arrives someplace but when an app is open application wok correctly but when the app in the background or closed nothing happened.
Is there any way to send a notification when the app is in the background or closed?

**Comment by Dev-hwang** [comment]
Currently uploaded plug-in can only perform geofencing while the app is alive. You can use the `WillStartForegroundTask` widget to prevent the app from closing when the back or home button is pressed, but not forcibly killed by the system. In the future, I will implement the service so that it can run in the background.

**Comment by fabidona** [comment]
Hi,
just a clarification: is WillStartForegroundTask widget working also for iOS ? Which app lifecycle cases are covered?
I can't figure out weather the iOS background location updates is supported on actual version.

Thank you so much for support
